### ISSUE TITLE
bower angularjs-scope.safeapply  error Arguments to path.join must be strings

### ISSUE THREAD

**Issue by LuisMDeveloper** [yearofmoo/AngularJS-Scope.SafeApply#8]
at AngularJS-Testing-Article npm install I get this error

``` zsh
bower angularjs-scope.safeapply#*            error Arguments to path.join must be strings
Stack trace:                                                                                                                            
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at GitHubResolver.GitResolver._cleanup (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/lib/core/resolvers/GitResolver.js:185:26)
    at /home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/lib/core/resolvers/GitResolver.js:74:25
    at Promise.apply (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:752:41)
    at /home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:1337:14
    at flush (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

Console trace:                                                                                                                          
Trace
    at StandardRenderer.error (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/bin/bower:109:18)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:808:24)
    at /home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:752:41)
    at /home/icarus/code/lab/AngularJS-Testing-Article/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.8
Node version: 0.10.29
OS: Linux 3.2.0-4-amd64 x64

```

**Comment by degafcon** [comment]
I fixed this by updating to Bower 1.3.3  (npm update -g bower, then modify package.json to ensure the bower module was also 1.3.3)
